### PR TITLE
Update inverse kinematics script with class InverseKinematics in biorbd in order to geenrate txt files

### PR DESCRIPTION
**Pull request by AurelienRenou**
Modified the script which generate txt files for q, qdot,qddot and tau in order to use InverseKinematics class form biorbd to generate q file

### CODE REVIEW

**Comment by Ipuch** [comment]
not ready yet right ?

**Comment by AurelienRenou** [comment]
I don't add the comment yet

**Comment by Ipuch** [comment]
Almost ready ?

**Comment by Ipuch** [comment]
ready ?

**Pull request merged**
